version: '3.8'
services:
  db:
    image: postgres:16.0-alpine3.17
    container_name: postgres-database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - app-network
  docker-example-app:
    container_name: docker-example-application
    image: docker-example-app:0.0.1-SNAPSHOT
    environment:
      HELLO_MESSAGE: Hello message from docker compose
      DATABASE_URL: jdbc:postgresql://db:5432/postgres
    depends_on:
      - db
    ports:
      - '8085:8085'
    networks:
      - app-network

volumes:
  db:
networks:
  app-network:
    name: docker-application-network
  db-network:
    name: docker-db-network
